export const CHARACTERS_DATA = [
  {
    id: 'jon-snow',
    name: 'Jon Snow',
    fullTitle: 'Lord Commander of the Night\'s Watch, King in the North',
    allegiance: 'House Stark, The Night\'s Watch',
    house: 'House Stark',
    status: 'Alive',
    biography: 'Raised as the bastard son of Ned Stark, Jon Snow found his calling at the Wall. Despite his vows, he was drawn into the wars of the realm, repeatedly proving himself a capable leader and warrior.',
    achievements: ['Defended the Wall against the Wildlings', 'Resurrected by Melisandre', 'Retook Winterfell in the Battle of the Bastards'],
    quote: 'Winter is coming.',
    relationships: ['Ned Stark (Father/Uncle)', 'Sansa Stark (Cousin)', 'Arya Stark (Cousin)', 'Daenerys Targaryen (Aunt/Lover)'],
    bg: '#1a1f26',
    accent: '#4a6380',
    sigilIcon: '🐺'
  },
  {
    id: 'daenerys-targaryen',
    name: 'Daenerys',
    fullTitle: 'Daenerys Stormborn of House Targaryen, the First of Her Name, Queen of the Andals and the First Men, Protector of the Seven Kingdoms, the Mother of Dragons, the Khaleesi of the Great Grass Sea, the Unburnt, the Breaker of Chains',
    allegiance: 'House Targaryen',
    house: 'House Targaryen',
    status: 'Deceased',
    biography: 'Exiled at birth, Daenerys survived a brutal childhood to become a Khaleesi and eventually a queen. Armed with three dragons, she sought to reclaim the Iron Throne and break the wheel of Westerosi politics.',
    achievements: ['Hatched three dragons', 'Conquered Slaver\'s Bay', 'Brought dragons back to Westeros'],
    quote: 'I will take what is mine with fire and blood.',
    relationships: ['Viserys Targaryen (Brother)', 'Khal Drogo (Husband)', 'Jon Snow (Nephew/Lover)', 'Jorah Mormont (Advisor)'],
    bg: '#2a0a0a',
    accent: '#c0392b',
    sigilIcon: '🐉'
  },
  {
    id: 'tyrion-lannister',
    name: 'Tyrion',
    fullTitle: 'Lord of Casterly Rock, Hand of the Queen',
    allegiance: 'House Lannister, House Targaryen',
    house: 'House Lannister',
    status: 'Alive',
    biography: 'Despised by his father and sister for his dwarfism and the death of his mother during his birth, Tyrion relied on his intellect, wit, and wealth to navigate the deadly politics of King\'s Landing.',
    achievements: ['Defended King\'s Landing at the Blackwater', 'Escaped execution', 'Became Hand to Daenerys Targaryen'],
    quote: 'I drink and I know things.',
    relationships: ['Tywin Lannister (Father)', 'Jaime Lannister (Brother)', 'Cersei Lannister (Sister)'],
    bg: '#2a220a',
    accent: '#d4a84b',
    sigilIcon: '🦁'
  },
  {
    id: 'arya-stark',
    name: 'Arya',
    fullTitle: 'Princess of Winterfell',
    allegiance: 'House Stark',
    house: 'House Stark',
    status: 'Alive',
    biography: 'Rejecting the traditional life of a highborn lady, Arya endured trauma and tragedy, eventually traveling to Braavos to train as a Faceless Man to avenge her family.',
    achievements: ['Assassinated Walder Frey', 'Defeated the Night King'],
    quote: 'Leave one wolf alive and the sheep are never safe.',
    relationships: ['Ned Stark (Father)', 'Sansa Stark (Sister)', 'Jon Snow (Brother/Cousin)', 'The Hound (Frenemy)'],
    bg: '#111',
    accent: '#4a6380',
    sigilIcon: '🗡'
  },
  {
    id: 'cersei-lannister',
    name: 'Cersei',
    fullTitle: 'Queen of the Andals and the First Men, Protector of the Seven Kingdoms',
    allegiance: 'House Lannister',
    house: 'House Lannister',
    status: 'Deceased',
    biography: 'Driven by ambition, a prophecy of doom, and a fierce love for her children, Cersei systematically destroyed her enemies, eventually claiming the Iron Throne for herself.',
    achievements: ['Destroyed the Great Sept of Baelor', 'Crowned herself Queen of the Seven Kingdoms'],
    quote: 'When you play the game of thrones, you win or you die.',
    relationships: ['Tywin Lannister (Father)', 'Jaime Lannister (Twin/Lover)', 'Tyrion Lannister (Brother)', 'Robert Baratheon (Husband)'],
    bg: '#2a0a0a',
    accent: '#d4a84b',
    sigilIcon: '👑'
  },
  {
    id: 'jaime-lannister',
    name: 'Jaime',
    fullTitle: 'Lord Commander of the Kingsguard',
    allegiance: 'House Lannister',
    house: 'House Lannister',
    status: 'Deceased',
    biography: 'Known as the Kingslayer for murdering the monarch he was sworn to protect, Jaime spent his life hiding his complicated morality behind a facade of arrogance.',
    achievements: ['Slew the Mad King, saving King\'s Landing', 'Led the Lannister armies'],
    quote: 'The things I do for love.',
    relationships: ['Cersei Lannister (Twin/Lover)', 'Tyrion Lannister (Brother)', 'Brienne of Tarth (Friend)'],
    bg: '#1a1a00',
    accent: '#d4a84b',
    sigilIcon: '⚔'
  }
]