export const HOUSES_DATA = [
  {
    id: 'stark',
    name: 'STARK',
    seat: 'Winterfell',
    words: '"Winter Is Coming"',
    region: 'The North',
    sigil: 'Grey Direwolf',
    founder: 'Bran the Builder',
    colors: ['#6b7a8d', '#c8d4e0'],
    accent: '#8fafc4',
    description: 'Wardens of the North, the Starks trace their blood to the First Men. Honour is their sword and the frozen wind their banner. They endure where others fall — patient as winter itself.',
    history: 'Founded during the Age of Heroes by Bran the Builder, who raised the Wall and built Winterfell. For thousands of years, they ruled as Kings in the North until Torrhen Stark knelt to Aegon the Conqueror to spare his people from dragonfire.',
    famousMembers: ['Ned Stark', 'Robb Stark', 'Arya Stark', 'Sansa Stark', 'Bran Stark', 'Jon Snow (by blood)'],
    timeline: [
      { year: 'Age of Heroes', event: 'Bran the Builder raises the Wall.' },
      { year: '1 AC', event: 'The King Who Knelt submits to Aegon.' },
      { year: '298 AC', event: 'Ned Stark named Hand of the King.' }
    ],
    sigil_url: 'images/one.jpg',
    bg: 'linear-gradient(135deg, #0d1117 0%, #1a2332 60%, #0d1117 100%)',
    borderColor: '#4a6380',
  },
  {
    id: 'lannister',
    name: 'LANNISTER',
    seat: 'Casterly Rock',
    words: '"Hear Me Roar"',
    region: 'The Westerlands',
    sigil: 'Golden Lion',
    founder: 'Lann the Clever',
    colors: ['#c9a84c', '#e8c97a'],
    accent: '#d4a84b',
    description: 'The wealthiest house in Westeros. Their lion does not merely roar — it devours. Power is their birthright, gold their language, and debt a weapon they wield with surgical precision.',
    history: 'Descended from Andal adventurers and Lann the Clever, a legendary trickster from the Age of Heroes who swindled Casterly Rock from House Casterly. Their immense wealth comes from the gold mines scattered across the Westerlands.',
    famousMembers: ['Tywin Lannister', 'Jaime Lannister', 'Cersei Lannister', 'Tyrion Lannister'],
    timeline: [
      { year: 'Age of Heroes', event: 'Lann the Clever takes Casterly Rock.' },
      { year: '281 AC', event: 'Tywin Lannister resigns as Hand of the King.' },
      { year: '283 AC', event: 'Jaime Lannister slays the Mad King.' }
    ],
    sigil_url: 'images/two.jpg',
    bg: 'linear-gradient(135deg, #1a1200 0%, #2a1f00 60%, #1a1200 100%)',
    borderColor: '#7a6130',
  },
  {
    id: 'targaryen',
    name: 'TARGARYEN',
    seat: 'Dragonstone',
    words: '"Fire and Blood"',
    region: 'The Crownlands',
    sigil: 'Three-Headed Dragon',
    founder: 'Aenar Targaryen',
    colors: ['#c41e3a', '#ff4466'],
    accent: '#c0392b',
    description: 'Blood of Old Valyria. They did not conquer Westeros — they burned it into submission. Dragon riders, dynasty builders, and the last of a world consumed by fire.',
    history: 'The last noble family of the Valyrian Freehold to survive the Doom. Aegon the Conqueror and his sister-wives united the Seven Kingdoms atop their dragons, forging the Iron Throne from the swords of their vanquished enemies.',
    famousMembers: ['Aegon the Conqueror', 'Aerys II (The Mad King)', 'Daenerys Targaryen', 'Rhaegar Targaryen'],
    timeline: [
      { year: '-114 AC', event: 'Targaryens relocate to Dragonstone.' },
      { year: '1 AC', event: 'Aegon conquers Westeros.' },
      { year: '283 AC', event: 'The Targaryen dynasty falls.' }
    ],
    sigil_url: 'images/three.png',
    bg: 'linear-gradient(135deg, #1a0000 0%, #2d0a0a 60%, #1a0000 100%)',
    borderColor: '#7a1a1a',
  },
  {
    id: 'baratheon',
    name: 'BARATHEON',
    seat: "Storm's End",
    words: '"Ours Is The Fury"',
    region: 'The Stormlands',
    sigil: 'Crowned Black Stag',
    founder: 'Orys Baratheon',
    colors: ['#e8c97a', '#f5e6c8'],
    accent: '#c9a84c',
    description: 'Born of storms, tempered by battle. The Baratheons seized the Iron Throne not through cunning but through iron will and a war hammer. Fury is not their weakness — it is their crown.',
    history: 'Founded by Orys Baratheon, rumored to be the bastard half-brother of Aegon the Conqueror. They defeated the Storm Kings and took their sigil and words as their own.',
    famousMembers: ['Robert Baratheon', 'Stannis Baratheon', 'Renly Baratheon'],
    timeline: [
      { year: '1 AC', event: 'Orys slays Argilac the Arrogant.' },
      { year: '282 AC', event: 'Robert\'s Rebellion begins.' },
      { year: '283 AC', event: 'Robert claims the Iron Throne.' }
    ],
    sigil_url: 'images/four.webp',
    bg: 'linear-gradient(135deg, #0a0a00 0%, #1f1c00 60%, #0a0a00 100%)',
    borderColor: '#5a5020',
  },
  {
    id: 'greyjoy',
    name: 'GREYJOY',
    seat: 'Pyke',
    words: '"We Do Not Sow"',
    region: 'The Iron Islands',
    sigil: 'Golden Kraken',
    founder: 'The Grey King (Legendary)',
    colors: ['#d4af37', '#8b8b6b'],
    accent: '#b8a040',
    description: 'Reavers of the sea. Iron men who bow to no king but the Drowned God. What they cannot make, they take. What they cannot take, they burn. The sea is their kingdom — all else is plunder.',
    history: 'Claiming descent from the Grey King of the Age of Heroes, the ironborn are raiders and reavers. House Greyjoy became lords paramount of the Iron Islands after Aegon\'s Conquest when the Ironborn were allowed to choose their leader.',
    famousMembers: ['Balon Greyjoy', 'Euron Greyjoy', 'Yara Greyjoy', 'Theon Greyjoy'],
    timeline: [
      { year: '2 AC', event: 'Greyjoys elected rulers of the Iron Islands.' },
      { year: '289 AC', event: 'Greyjoy\'s Rebellion is crushed.' }
    ],
    sigil_url: 'images/five.jpg',
    bg: 'linear-gradient(135deg, #050810 0%, #0a1020 60%, #050810 100%)',
    borderColor: '#3a4a5a',
  },
  {
    id: 'tyrell',
    name: 'TYRELL',
    seat: 'Highgarden',
    words: '"Growing Strong"',
    region: 'The Reach',
    sigil: 'Golden Rose',
    founder: 'Harlen Tyrell',
    colors: ['#4a7c3f', '#7ab648'],
    accent: '#5a9e48',
    description: 'The richest lords of the Reach, whose roses feed the realm. Behind beauty and abundance lies a house of ruthless ambition — growing strong in gardens, and stronger still in schemes.',
    history: 'Originally stewards to House Gardener. When King Mern IX died on the Field of Fire, Harlen Tyrell surrendered Highgarden to Aegon the Conqueror and was rewarded with the castle and dominion over the Reach.',
    famousMembers: ['Olenna Tyrell', 'Mace Tyrell', 'Margaery Tyrell', 'Loras Tyrell'],
    timeline: [
      { year: '1 AC', event: 'Tyrells granted dominion over the Reach.' },
      { year: '299 AC', event: 'Tyrells ally with the Lannisters.' }
    ],
    sigil_url: 'images/six.jpg',
    bg: 'linear-gradient(135deg, #030a00 0%, #0a1800 60%, #030a00 100%)',
    borderColor: '#2a4a20',
  },
  {
    id: 'martell',
    name: 'MARTELL',
    seat: 'Sunspear',
    words: '"Unbowed, Unbent, Unbroken"',
    region: 'Dorne',
    sigil: 'Red Sun Pierced By A Spear',
    founder: 'Morgan Martell',
    colors: ['#e67e22', '#d35400'],
    accent: '#d35400',
    description: 'Fierce and fiercely independent. The Dornish are the only people Aegon the Conqueror could not break. Passionate, lethal, and bound by ancient, burning blood.',
    history: 'United Dorne alongside the warrior queen Nymeria of the Rhoynar. Dorne successfully resisted Aegon\'s Conquest through guerrilla warfare, only joining the Seven Kingdoms over a century later through marriage, not conquest.',
    famousMembers: ['Doran Martell', 'Oberyn Martell', 'Elia Martell'],
    timeline: [
      { year: '-700 BC', event: 'Nymeria marries Mors Martell.' },
      { year: '1 AC', event: 'Dorne successfully resists Aegon.' },
      { year: '187 AC', event: 'Dorne joins the Seven Kingdoms.' }
    ],
    sigil_url: 'images/five.jpg', // Placeholder asset
    bg: 'linear-gradient(135deg, #1a0a00 0%, #2b1200 60%, #1a0a00 100%)',
    borderColor: '#8a4000',
  }
]